kind: ethereum
name: erc404
network: {{network}}
source:
  address: "{{address}}"
  abi: erc404
  startBlock: {{startBlock}}
mapping:
  kind: ethereum/events
  apiVersion: 0.0.7
  language: wasm/assemblyscript
  entities:
    - Erc404Approval
    - Erc404ApprovalForAll
    - Erc404OwnershipTransferred
    - Erc404Transfer
    - Erc404TransferBatch
    - Erc404TransferSingle
    - Erc404URI
  abis:
    - name: erc404
      file: ./abis/erc404.json
  eventHandlers:
    - event: Approval(indexed address,indexed address,uint256)
      handler: handleApproval
    - event: ApprovalForAll(indexed address,indexed address,bool)
      handler: handleApprovalForAll
    - event: OwnershipTransferred(indexed address,indexed address)
      handler: handleOwnershipTransferred
    - event: Transfer(indexed address,indexed address,uint256)
      handler: handleTransfer
    - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
      handler: handleTransferBatch
    - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
      handler: handleTransferSingle
    - event: URI(string,indexed uint256)
      handler: handleURI
  file: ./src/erc-404.ts