kind: ethereum
name: erc721
network: {{network}}
source:
  address: "{{address}}"
  abi: erc721
  startBlock: {{startBlock}}
mapping:
  kind: ethereum/events
  apiVersion: 0.0.7
  language: wasm/assemblyscript
  entities:
    - Erc721Approval
    - Erc721ApprovalForAll
    - Erc721AwardItem
    - Erc721Burn
    - Erc721OwnershipTransferred
    - Erc721SetTokenCID
    - Erc721Transfer
  abis:
    - name: erc721
      file: ./abis/erc721.json
  eventHandlers:
    - event: Approval(indexed address,indexed address,indexed uint256)
      handler: handleApproval
    - event: ApprovalForAll(indexed address,indexed address,bool)
      handler: handleApprovalForAll
    - event: AwardItem(address,string,uint256)
      handler: handleAwardItem
    - event: Burn(uint256)
      handler: handleBurn
    - event: OwnershipTransferred(indexed address,indexed address)
      handler: handleOwnershipTransferred
    - event: SetTokenCID(uint256,string)
      handler: handleSetTokenCID
    - event: Transfer(indexed address,indexed address,indexed uint256)
      handler: handleTransfer
  file: ./src/erc-721.ts